#!/usr/bin/env bash
# topo-hint.sh — PreToolUse hook for Claude Code (Glob/Grep)
# Injects lightweight file hints when Claude searches for files.
# Generated by `topo init`. Safe to customise — re-run `topo init --force` to reset.

set -euo pipefail

INPUT=$(cat)
TOOL=$(echo "$INPUT" | jq -r '.tool_name // empty')

# Extract the search query from the tool input
QUERY=""
if [ "$TOOL" = "Glob" ]; then
  QUERY=$(echo "$INPUT" | jq -r '.tool_input.pattern // empty')
elif [ "$TOOL" = "Grep" ]; then
  QUERY=$(echo "$INPUT" | jq -r '.tool_input.pattern // empty')
fi

# Skip short or empty queries
if [ -z "$QUERY" ] || [ ${#QUERY} -lt 3 ]; then
  exit 0
fi

# Run topo quick with fast preset, fewer results for hints
RESULTS=$(topo quick "$QUERY" --format compact --preset fast --top 5 2>/dev/null) || true

if [ -n "$RESULTS" ]; then
  jq -n --arg ctx "Topo suggests these files may also be relevant:
$RESULTS" \
    '{"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":$ctx}}'
fi
