#!/usr/bin/env bash
# topo-track.sh — PostToolUse hook for Claude Code (Read)
# Tracks which files Claude actually opens for `topo gain` analytics.
# Generated by `topo init`. Safe to customise — re-run `topo init --force` to reset.

set -euo pipefail

INPUT=$(cat)
TOOL=$(echo "$INPUT" | jq -r '.tool_name // empty')

# Only track Read tool usage
if [ "$TOOL" != "Read" ]; then
  exit 0
fi

FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Append to stats log
STATS_DIR="${TOPO_ROOT:-.}/.topo"
mkdir -p "$STATS_DIR"

jq -n --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
      --arg event "file_read" \
      --arg path "$FILE_PATH" \
  '{"timestamp":$ts,"event":$event,"path":$path}' \
  >> "$STATS_DIR/stats.jsonl"
