#!/usr/bin/env bash
# topo-context.sh — UserPromptSubmit hook for Claude Code
# Automatically injects relevant file suggestions when a prompt is submitted.
# Generated by `topo init`. Safe to customise — re-run `topo init --force` to reset.

set -euo pipefail

INPUT=$(cat)
PROMPT=$(echo "$INPUT" | jq -r '.prompt // empty')

# Skip short/meta prompts (commands, single words, empty)
if [ -z "$PROMPT" ] || [ ${#PROMPT} -lt 15 ]; then
  exit 0
fi

# Run topo quick with fast preset for low latency
RESULTS=$(topo quick "$PROMPT" --format compact --preset fast --top 10 2>/dev/null) || true

if [ -n "$RESULTS" ]; then
  jq -n --arg ctx "Topo file suggestions (ranked by relevance):
$RESULTS" \
    '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":$ctx}}'
fi
